version: "2.4"

services: 
  trtis-server-container:
    image: trtis-server
    build:
      context: ./docker
      dockerfile: ./server/Dockerfile
    container_name: trtis-server-container  # prevent to set the default docker container name
    volumes: 
      - ./model_repository:/models
      - ./dataset:/dataset
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    ulimits: 
      memlock: -1
      stack: 67108864
    shm_size: "1g"
    entrypoint: "/opt/tensorrtserver/nvidia_entrypoint.sh trtserver 
                  --model-repository=/models --model-control-mode=explicit 
                  --load-model=face_recognition_model
                  --load-model=mecab_model
                  --load-model=sample_instance
                  --load-model=sample_sequence
                  --log-verbose=1" # TODO : Should not set entrypoint, get parameter from commandline
  trtis-client-container:
    image: trtis-client
    build: ./docker/client
    container_name: trtis-client-container
    volumes: 
      - ./src/client:/workspace/custom_client
      - ./dataset:/workspace/dataset
    tty: true
    ports:
      - "8501:8501"
  data-uploader-container:
    image: data-uploader
    build: 
      context: ./docker
      dockerfile: ./data_uploader/Dockerfile
    container_name: data-uploader-container
    volumes:
      - ./src/data_uploader:/workspace/src
      - ./dataset:/workspace/dataset
    ports:
      - "8502:8502"
    entrypoint: "bash entry.sh"
  trtis-custom-backend-build-container:
    image: trtis-custom-backend-build
    build: 
      context: ./docker
      dockerfile: ./custom_backend/Dockerfile
    container_name: trtis-custom-backend-build-container
    volumes: 
      - ./src/custom_backend:/workspace/custom_backend
    network_mode: host
    tty: true
