name: "sample_instance"
platform: "custom"
default_model_filename: "libsample_instance.so"
max_batch_size: 1
input [
  {
    name: "INPUT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]